### PR TITLE
Save and Load Parameters from JSON

### PR DESCRIPTION
**Pull request by silentpatrik**
added feature for saving and loading config files like "projects". See readme for details. 

Btw. i really like this project, its exactly what i need for my own purposes and i have searched long time for something similar. Im not good enough with using the models to create my own project.
If you dont mind, i would like to contribute with some small features now and then, next up, grids :).

### CODE REVIEW

**Comment by Beinsezii** [comment]
I like the idea. I was originally going to make a `defaults.json` but I think this is better.

As it stands, this is incomplete as it won't parse non-QDParam args which means it can't save system flags. While you could conditionally save these all and match to exclude options that don't make sense like `print` and `include`, it's probably better if all the valid options are converted to QDParams first.

Additionally, I feel like having two unique CLI args is unnecessary and limiting. It would be more robust to set `include` with `nargs='*'` then attempt to decode the bytes as valid JSON before falling back to PngInfo. That way you could for example
```nushell
./quickdif.sh -I defaults.json reference.png style.json -s 30
```
to apply each JSON's and PNG's params in sequence before cli overrides. Additionally using FileType as the typing allows piping serialized data such as
```nushell
open big_db.xml | get styles.fantasy | to json | ./quickdif.sh -I -`
```

Pretty soon I'm going to go back and convert most of the sys args to QDParams because [this line gives me depression](https://github.com/Beinsezii/quickdif/blob/d0b2eb329636f21e7cf60eb78c72d4431c6156e5/quickdif.py#L211), so I could probably just cherry this in during that process.

**Comment by Beinsezii** [comment]
On the topic of grids, the actual iteration logic would be easy now because QDParams does most of that already. You'd just need a flag for specifying which params to make the grid[s] in something like `grid X [Y] [Z]` such as
```nushell
./quickdif.sh "photo of a kitten" -s 10 20 30 -S dpm dpm2 --grid 'steps' 'sampler'
```

The real labor will be in rendering the labels assuming PIL doesn't have any convenience functions for that. Have to make sure all the headers are aligned to each image and don't clip while being wrapped to use as little X or Y space as possible depending on the axis. That's the part that would take me personally the most time to implement at a high enough standard.

**Comment by silentpatrik** [comment]
> As it stands, this is incomplete as it won't parse non-QDParam args which means it can't save system flags. 
Aha, i tottally missed this workflow, its more like "recepies" than config-templating. 

The only reason i stored as i did was i had problems with gettings things to work, it was quite a challenge to get it to work at all and i redid it two times before i got it as its now. 

Question, since im new to the codebase, i dont really understad QDParams. It seems now it is config for the models but it is also used for command line arguments? Or is there any other reason not to have all variables as argparse settings?

**Comment by Beinsezii** [comment]
QDParams exist to unify everything instead of having checks for each parameter in 5 different spots.

Before you'd build everything in argparse, then have hardcoded lists on which to iterate, which to add to meta, etc all across the file. With QDParams it's all localized to the master list so you can just add a new QDParam and automatically get the argparse, iteration, png meta reading...

The conversion was all done in one sitting at 4 am, so you can see the entire thing [in one commit here](https://github.com/Beinsezii/quickdif/commit/61f5f56972e28f2b4e12a97810e9de51bb1ba37d). This was only a few days ago so I haven't evolved it much beyond the MVP.

**Comment by Beinsezii** [comment]
Implemented with all of the above in 4ebfba5

**Comment by silentpatrik** [comment]
> Implemented with all of the above in [4ebfba5](https://github.com/Beinsezii/quickdif/commit/4ebfba561b17e1fd6d54d738a3c87eacde7e0d8b)

Wow, you nailed it! Gj!

**Pull request closed without merging**
